### ISSUE TITLE
Various bugs and improvements 

### ISSUE THREAD

**Issue by joshuamotoaki** [joshuamotoaki/tiger-junction#15]
The TigerSnatch link does not work. On weird aspect ratio devices, the bottom of the top bar gets cut off. The search by "title/code" is useless: remove. Advanced search button needs to be made more obvious. Show locations on schedule. Fix accessibility problem when colors are changed. Figure out way to trigger search result re-render when sort by setting is changed. Fix rating parameters not hard resetting when clicking the reset button. Implement filter by adjusted rating. Make wording for adjusted rating consistent. Double tabbing on minimal card buttons. I don't like the style of the links, make more beautiful.

**Comment by m-ichelleliu** [comment]
Can you make this into a checklist it's hard to read

**Comment by joshuamotoaki** [comment]
TigerSnatch links and "title/code" search fixed in #16

**Comment by joshuamotoaki** [comment]
Resolved in #18
