### ISSUE TITLE
Highlight corresponding course in calendar when hovering over that course in the saved courses list

### ISSUE THREAD

**Issue by m-ichelleliu** [joshuamotoaki/tiger-junction#61]
<img width="228" alt="image" src="https://github.com/joshuamotoaki/tiger-junction/assets/91390445/15861b94-87ee-4633-9559-a48528c3be40">

my schedule looks like this rn and i cannot for the life of me figure out which course is which T_T

when i hovered over courses on the saved courses list, i was hoping it would highlight the corresponding courses on the calendar

but alas it does not

and when i hover over the course in the calendar, i still can't see its name, so i actually can't figure out what courses are at what time on my calendar right now unless i inspect element n mess w stuff

**Comment by joshuamotoaki** [comment]
It does bidirectional highlighting now. I've decided not to implement tooltips on hover because it would make quality of experience worse for everyone who doesn't overload their schedules like this lol (this is not the intended purpose of the app 😭  do you want to bring the pin feature back?)

**Comment by m-ichelleliu** [comment]
truuu dat
nah im just stress testing it on g
wahts the pin feature
