### ISSUE TITLE
Please include # of reviews by the average ratings

### ISSUE THREAD

**Issue by m-ichelleliu** [joshuamotoaki/tiger-junction#9]
<img width="288" alt="image" src="https://github.com/joshuamotoaki/tiger-junction/assets/91390445/deb17c8b-c95c-4a5a-9d9d-35cc5ee5ca92">

In search results

**Comment by joshuamotoaki** [comment]
Updated. The actual number of reviews in not a metric I can obtain, but rather only the number of comments (which is usually not everyone who left a review). Adjusted rating is calculated using an approximated adjustment formula; this may be made more precise in the future, but would require some backend changes.

**Comment by m-ichelleliu** [comment]
why did i read this in ur voice
